### ISSUE TITLE
运行报错Maximum amount of retries reached

### ISSUE THREAD

**Issue by En0t5** [Taonn/EmailAll#13]
python3 emailall.py --domain baidu.com run

EmailALl is a powerful Emails integration tool
 _____                _ _  ___  _ _
|  ___|              (_) |/ _ \| | | {v1.0 #dev}
| |__ _ __ ___   __ _ _| / /_\ \ | |
|  __| '_ ` _ \ / _` | | |  _  | | |
| |__| | | | | | (_| | | | | | | | |
\____/_| |_| |_|\__,_|_|_\_| |_/_|_| By Microtao.

[*] Starting EmailAll @ 2022-08-18 13:42:39

13:42:39,388 [INFOR] utils:44 - Checking network environment
13:42:40,556 [INFOR] collect:45 - Start collecting Emails of baidu.com
Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "E:\Lib\Python\Python38\lib\site-packages\fake_useragent\utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "E:\Lib\Python\Python38\lib\site-packages\fake_useragent\utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range
Traceback (most recent call last):
  File "E:\Lib\Python\Python38\lib\site-packages\fake_useragent\utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "E:\Lib\Python\Python38\lib\site-packages\fake_useragent\utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Lib\Python\Python38\lib\urllib\request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "E:\Lib\Python\Python38\lib\http\client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "E:\Lib\Python\Python38\lib\http\client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "E:\Lib\Python\Python38\lib\http\client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "E:\Lib\Python\Python38\lib\http\client.py", line 1007, in _send_output
    self.send(msg)
  File "E:\Lib\Python\Python38\lib\http\client.py", line 947, in send
    self.connect()
  File "E:\Lib\Python\Python38\lib\http\client.py", line 1414, in connect
    super().connect()
  File "E:\Lib\Python\Python38\lib\http\client.py", line 918, in connect
    self.sock = self._create_connection(
  File "E:\Lib\Python\Python38\lib\socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "E:\Lib\Python\Python38\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Lib\Python\Python38\lib\site-packages\fake_useragent\utils.py", line 64, in get
    with contextlib.closing(urlopen(
  File "E:\Lib\Python\Python38\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "E:\Lib\Python\Python38\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "E:\Lib\Python\Python38\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "E:\Lib\Python\Python38\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "E:\Lib\Python\Python38\lib\urllib\request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "E:\Lib\Python\Python38\lib\urllib\request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11002] getaddrinfo failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "emailall.py", line 94, in <module>
    fire.Fire(EmailAll)
  File "E:\Lib\Python\Python38\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "E:\Lib\Python\Python38\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "E:\Lib\Python\Python38\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "emailall.py", line 79, in run
    self.main()
  File "emailall.py", line 59, in main
    collect.run()
  File "E:\Test_tools\EmailAll\modules\collect.py", line 47, in run
    self.import_func()
  File "E:\Test_tools\EmailAll\modules\collect.py", line 37, in import_func
    import_object = importlib.import_module(module)
  File "E:\Lib\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\Test_tools\EmailAll\modules\datasets\Emailf.py", line 8, in <module>
    from common.search import Search
  File "E:\Test_tools\EmailAll\common\search.py", line 5, in <module>
    from modules.module import Module
  File "E:\Test_tools\EmailAll\modules\module.py", line 18, in <module>
    ua = UserAgent()
  File "E:\Lib\Python\Python38\lib\site-packages\fake_useragent\fake.py", line 69, in __init__
    self.load()
  File "E:\Lib\Python\Python38\lib\site-packages\fake_useragent\fake.py", line 75, in load
    self.data = load_cached(
  File "E:\Lib\Python\Python38\lib\site-packages\fake_useragent\utils.py", line 250, in load_cached
    update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
  File "E:\Lib\Python\Python38\lib\site-packages\fake_useragent\utils.py", line 245, in update
    write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
  File "E:\Lib\Python\Python38\lib\site-packages\fake_useragent\utils.py", line 187, in load
    ret = json.loads(get(
  File "E:\Lib\Python\Python38\lib\site-packages\fake_useragent\utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached

**Comment by ccc-f** [comment]
pip install -U fake-useragent
